<?php

/**
 * PluginAnWebAnalyticsTypeEventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAnWebAnalyticsTypeEventTable extends AnWebAnalyticsEventTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAnWebAnalyticsTypeEventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAnWebAnalyticsTypeEvent');
    }
}