<?php

/**
 * PluginAnWebAnalyticsArticleImpressionEventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAnWebAnalyticsArticleImpressionEventTable extends AnWebAnalyticsEventTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAnWebAnalyticsArticleImpressionEventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAnWebAnalyticsArticleImpressionEvent');
    }
}