<?php

/**
 * PluginAnWebAnalyticsVisitDmPageAssocTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAnWebAnalyticsVisitDmPageAssocTable extends AnWebAnalyticsVisitPageAssocTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAnWebAnalyticsVisitDmPageAssocTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAnWebAnalyticsVisitDmPageAssoc');
    }
    
    
		public function connectPageWithVisit(DmPage $page, AnWebAnalyticsVisit $visit) {      
      
        $connection = new AnWebAnalyticsVisitDmPageAssoc();
        $connection->setVisitCookieId($visit->getVisitCookieId());
        $connection->setPageId($page->getId());
        $connection->save();
      
      return $connection;
    }
    
}