<?php

/**
 * PluginAnWebAnalyticsPageElementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAnWebAnalyticsPageElementTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAnWebAnalyticsPageElementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAnWebAnalyticsPageElement');
    }
    
    
    
    public function fetchLayoutPageElements($layoutId) {
    
    	$q = $this->createQuery('pe INDEXBY pe.dom_id')
    				->select('pe.dom_id, pe.settings')
    				->where('pe.dm_layout_id = ?', $layoutId);
    	
			return $q->fetchArray();
    }
    
}