<?php

/**
 * PluginAnWebAnalyticsVisitorDmUserAssocTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAnWebAnalyticsVisitorDmUserAssocTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAnWebAnalyticsVisitorDmUserAssocTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAnWebAnalyticsVisitorDmUserAssoc');
    }
    
    
    public function connectDmUserWithVisitor(AnWebAnalyticsVisitor $visitor, DmUser $user) {
    
      $q = $this->createQuery('c')
            ->select('c.user_cookie_id')
            ->where('c.user_cookie_id = ?', $visitor->getUserCookieId())
            ->andWhere('c.dm_user_id = ?', $user->getId());
            
      if (! $q->fetchValue()) {
      
        $connection = new AnWebAnalyticsVisitorDmUserAssoc();
        $connection->setUserCookieId($visitor->getUserCookieId());
        $connection->setDmUserId($user->getId());
        $connection->save();
      }
    }
    
}