<?php

/**
 * PluginAnWebAnalyticsAdminHomeWindowTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAnWebAnalyticsAdminHomeWindowTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAnWebAnalyticsAdminHomeWindowTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAnWebAnalyticsAdminHomeWindow');
    }
}