<?php

/**
 * PluginAnWebAnalyticsTextSelectEventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAnWebAnalyticsTextSelectEventTable extends AnWebAnalyticsEventTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAnWebAnalyticsTextSelectEventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAnWebAnalyticsTextSelectEvent');
    }
}