<?php

/**
 * PluginAnWebAnalyticsVisitorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAnWebAnalyticsVisitorTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAnWebAnalyticsVisitorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAnWebAnalyticsVisitor');
    }
    
    
    public function countQuery() {
    	
    	$q = $this->createQuery('v')
    				->select('COUNT(v.user_cookie_id), v.created_at');
    	
    	return $q;
    }
    
    
    public function fetchOsInUse() {
    	
    	$q = $this->createQuery('v')
    					->select('DISTINCT(v.os)');
    	
    	return $q->fetchValue();
    }
    
    
    public function fetchBrowsersInUse() {
    	
    	$q = $this->createQuery('v')
    					->select('DISTINCT(v.browser)')
    					->orderBy('v.browser ASC');
    	
    	$browsers = $q->fetchValue();
    	$grouped = array();
    	foreach ($browsers as $k => $browser) {
    		
    		list($name, $ver) = explode('|', $browser);
    		if (! isset($grouped[$name])) {
    			
    			$grouped[$name] = $name;
    		}
    		
    		$grouped[$browser] = $name.' '.$ver;
    	}
    	
    	return $grouped;
    }
    
}