<?php

/**
 * PluginAnWebAnalyticsClickEventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAnWebAnalyticsClickEventTable extends AnWebAnalyticsEventTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAnWebAnalyticsClickEventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAnWebAnalyticsClickEvent');
    }
}