<?php

/**
 * PluginAnWebAnalyticsImpressionEventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAnWebAnalyticsImpressionEventTable extends AnWebAnalyticsEventTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAnWebAnalyticsImpressionEventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAnWebAnalyticsImpressionEvent');
    }
}