<?php

/**
 * PluginAnWebAnalyticsEventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAnWebAnalyticsEventTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAnWebAnalyticsEventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAnWebAnalyticsEvent');
    }
    
    
    public function countQuery() {
    
    	$q = $this->createQuery('e')
    				->select('e.id, COUNT(e.id), e.created_at');
    				
			return $q;
    }
    
}