<?php

/**
 * PluginAnWebAnalyticsVisitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAnWebAnalyticsVisitTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAnWebAnalyticsVisitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAnWebAnalyticsVisit');
    }
    
    
    public function countQuery() {
    	
    	$q = $this->createQuery('v')
    				->select('COUNT(v.visit_cookie_id), v.created_at');
    	
    	return $q;
    }
    
    
    public function fetchReferersInUse() {
    	
    	$q = $this->createQuery();
    }
    
}