<?php

/**
 * PluginAnWebAnalyticsVisitPageAssocTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAnWebAnalyticsVisitPageAssocTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAnWebAnalyticsVisitPageAssocTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAnWebAnalyticsVisitPageAssoc');
    }
    
    
    
    
    
    
    
    public function getPrevious(AnWebAnalyticsVisit $visit) {
    
    	$q = $this->createQuery('c')
            ->where('c.visit_cookie_id = ?', $visit->getVisitCookieId())
            ->orderBy('c.datestart DESC');
            
			return $q->fetchOne();
    }
    
    
    
    public function countQuery() {
    	 
    	$q = $this->createQuery('vpa')
    				->select('COUNT(vpa.id), vpa.datestart, vpa.datestart AS created_at');
    	
    	return $q;
    }
    
    
    
    
    
    
        
}