generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: AnWebAnalyticsPageElement
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: an_web_analytics_page_element
    with_doctrine_route: false
    config:
      actions: ~
      fields: {  }
      list:
        loremize: false
        display:
          - '=name'
          - page_id
          - _settings
        sort:
          - name
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - name
          - page_id
          - settings
      form:
        display:
          NONE: [name, page_id]
          'Events That Occured during Visits': [wA_events_list]
          Others: [settings]
        class: AnWebAnalyticsPageElementAdminForm
        fields: {  }
      edit: ~
      new: ~
