generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: AnWebAnalyticsPollVoteEvent
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: an_web_analytics_poll_vote_event
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        an_poll_answers_list:
          label: 'Poll Answers'
      list:
        actions:        {  }
        batch_actions:  {  }
        display:
          - page_id
          - visitor_cookie_id
          - visit_cookie_id
          - poll_id
          - an_poll_answers_list
          - visitor_ip
          - created_at
        sort:
          - created_at
          - desc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - page_id
          - visitor_cookie_id
          - visitor_ip
          - visit_cookie_id
          - poll_id
          - created_at
      form:
        display:
          NONE: [page_id, page_element_id, visitor_cookie_id, visit_cookie_id, poll_id]
          'Typed text': [typed_text]
          'Selected text': [selected_text]
          'Poll Answers': [an_poll_answers_list]
          Others: [visitor_ip, page_x, page_y, article_id, comment_id, page, rate]
        class: AnWebAnalyticsPollVoteEventAdminForm
        fields: {  }
      edit: ~
      new: ~
