generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: AnWebAnalyticsTypeEvent
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: an_web_analytics_type_event
    with_doctrine_route: false
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - page_id
          - page_element_id
          - visitor_cookie_id
          - visit_cookie_id
          - visitor_ip
          - page_x
          - page_y
          - typed_text
          - created_at
        sort:
          - created_at
          - desc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - id
          - page_id
          - visitor_cookie_id
          - visitor_ip
          - visit_cookie_id
          - page_element_id
          - page_x
          - page_y
          - typed_text
          - created_at
      form:
        display:
          NONE: [page_id, page_element_id, visitor_cookie_id, visit_cookie_id]
          'Typed text': [typed_text]
          'Selected text': [selected_text]
          Others: [visitor_ip, page_x, page_y, article_id, page, rate, poll_id]
        class: AnWebAnalyticsTypeEventAdminForm
        fields: {  }
      edit: ~
      new: ~
